version: '3.8'

services:
  # DevContainer pour développement NU Fridge
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    ports:
      - "5173:5173"  # Vite dev server
      - "3001:3001"  # Backend API
      - "8080:8080"  # Nginx
    environment:
      - TENANT=nufridge
      - TENANT_NAME=NU Fridge
    working_dir: /workspace

  # Hub MQTT Fleet Core (service générique)
  hub:
    image: acrfleetcoredev.azurecr.io/fleetcore-hub:latest
    ports:
      - "1883:1883"
      - "9001:9001"

  # Backend SmartKiosk Core avec customizations tenant
  backend:
    image: acrfleetcoredev.azurecr.io/fleetcore-smartkiosk-backend:latest
    ports:
      - "3001:3001"
    environment:
      - TENANT=nufridge
      - TENANT_NAME=NU Fridge
      - MQTT_BROKER_URL=mqtt://hub:1883
    volumes:
      - ./src:/app/tenant:ro  # Mount tenant customizations
    depends_on:
      - hub

  # Frontend SmartKiosk Core avec surcharges NU Fridge
  frontend:
    image: acrfleetcoredev.azurecr.io/fleetcore-smartkiosk-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - TENANT=nufridge
      - TENANT_NAME=NU Fridge
      - VITE_API_URL=http://backend:3001
    volumes:
      - ./src:/app/tenant:ro  # Mount tenant customizations
    depends_on:
      - backend

  # Nginx SmartKiosk Core avec configuration tenant
  nginx:
    image: acrfleetcoredev.azurecr.io/fleetcore-smartkiosk-nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - TENANT=nufridge
      - NGINX_BACKEND_HOST=backend
      - NGINX_FRONTEND_HOST=frontend
    volumes:
      - ./src:/app/tenant:ro  # Mount tenant customizations
    depends_on:
      - frontend
      - backend