version: '3.8'

services:
  fridge-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    environment:
      - FLEET_CORE_PATH=/workspace/.fleet-core
      - TENANT=NU
      - PROJECT=Fridge
    ports:
      - "5174:5174"  # Simulator
    command: sleep infinity

  # Services Fleet Core intégrés
  fleet-backend:
    image: acrfleetcoredev.azurecr.io/fleet-core/backend:dev-amd64
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  fleet-hub:
    image: acrfleetcoredev.azurecr.io/fleet-core/hub:dev-amd64
    ports:
      - "1883:1883"
      - "9001:9001"