#!/bin/bash
# Sync dev-manager - Extract reusable functions from Fleet Core
# Exécuté automatiquement à postStartCommand

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}[Sync] ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}[Sync] ✅ $1${NC}"
}

print_error() {
    echo -e "${RED}[Sync] ❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}[Sync] ⚠️  $1${NC}"
}

# Configuration
FLEET_CORE_PATH="${FLEET_CORE_PATH:-/workspace/.fleet-core}"
CORE_FUNCTIONS_FILE="/workspace/scripts/core-functions.sh"
FRONTEND_DEV_MANAGER="$FLEET_CORE_PATH/modules-core/Frontend/dev-manager.sh"

extract_reusable_functions() {
    local source_file="$1"
    local output_file="$2"

    if [[ ! -f "$source_file" ]]; then
        print_error "Source file not found: $source_file"
        return 1
    fi

    print_info "Extracting reusable functions from $source_file..."

    # Create header for core functions file
    cat > "$output_file" << 'EOF'
#!/bin/bash
# Core Functions - Extracted from Fleet Core dev-manager
# Auto-generated by sync-dev-manager.sh - DO NOT EDIT MANUALLY

# Colors for output (from Fleet Core)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}[Tenant] ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}[Tenant] ✅ $1${NC}"
}

print_error() {
    echo -e "${RED}[Tenant] ❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}[Tenant] ⚠️  $1${NC}"
}

EOF

    # Extract functions between markers
    if grep -q "# REUSABLE_FUNCTIONS_START" "$source_file"; then
        print_info "Found reusable functions markers"
        sed -n '/# REUSABLE_FUNCTIONS_START/,/# REUSABLE_FUNCTIONS_END/p' "$source_file" >> "$output_file"
        print_success "Functions extracted successfully"
    else
        print_warning "No reusable functions markers found in $source_file"
        print_info "Creating empty functions file"
    fi

    # Make executable
    chmod +x "$output_file"
}

main() {
    print_info "Syncing dev-manager functions from Fleet Core..."

    # Check if Fleet Core is available
    if [[ ! -d "$FLEET_CORE_PATH" ]]; then
        print_error "Fleet Core not found at $FLEET_CORE_PATH"
        print_info "Run scripts/setup-fleet-core.sh first"
        exit 1
    fi

    # Extract reusable functions
    extract_reusable_functions "$FRONTEND_DEV_MANAGER" "$CORE_FUNCTIONS_FILE"

    print_success "Dev-manager sync completed"
    print_info "Core functions available at: $CORE_FUNCTIONS_FILE"
}

# Execute main function
main "$@"